// Institutional-grade real estate datasets for Gujarat (Ahmedabad, Surat) and Maharashtra (Mumbai, Pune)
// Also contains reference data for Bangalore and Hyderabad

const builders = [
  {
    _id: "60c72b2f9b1d8b2a3c8e4d01",
    builderName: "Adani Realty",
    panNumber: "AADCA1294F",
    registrationCount: 14,
    completedProjects: 11,
    ongoingProjects: 2,
    delayedProjects: 1,
    averageDelayMonths: 4,
    trustScore: 92,
    state: "Gujarat"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d02",
    builderName: "Ganesh Housing",
    panNumber: "AGHCP9823K",
    registrationCount: 18,
    completedProjects: 16,
    ongoingProjects: 2,
    delayedProjects: 0,
    averageDelayMonths: 0,
    trustScore: 98,
    state: "Gujarat"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d03",
    builderName: "Lodha Group",
    panNumber: "ALODP4829L",
    registrationCount: 42,
    completedProjects: 28,
    ongoingProjects: 9,
    delayedProjects: 5,
    averageDelayMonths: 8,
    trustScore: 84,
    state: "Maharashtra"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d04",
    builderName: "Godrej Properties",
    panNumber: "AGODP7731M",
    registrationCount: 31,
    completedProjects: 24,
    ongoingProjects: 6,
    delayedProjects: 1,
    averageDelayMonths: 3,
    trustScore: 94,
    state: "Maharashtra"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d05",
    builderName: "Kolte-Patil Developers",
    panNumber: "AKPDC9204G",
    registrationCount: 22,
    completedProjects: 15,
    ongoingProjects: 4,
    delayedProjects: 3,
    averageDelayMonths: 11,
    trustScore: 78,
    state: "Maharashtra"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d06",
    builderName: "Rajhans Group",
    panNumber: "ARJHG3389J",
    registrationCount: 11,
    completedProjects: 7,
    ongoingProjects: 3,
    delayedProjects: 1,
    averageDelayMonths: 5,
    trustScore: 88,
    state: "Gujarat"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d07",
    builderName: "Sunteck Realty",
    panNumber: "ASRTL5432D",
    registrationCount: 15,
    completedProjects: 10,
    ongoingProjects: 3,
    delayedProjects: 2,
    averageDelayMonths: 14,
    trustScore: 74,
    state: "Maharashtra"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d08",
    builderName: "L&T Realty",
    panNumber: "ALNTR9948E",
    registrationCount: 25,
    completedProjects: 22,
    ongoingProjects: 3,
    delayedProjects: 0,
    averageDelayMonths: 0,
    trustScore: 99,
    state: "Maharashtra"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d09",
    builderName: "Tata Housing",
    panNumber: "ATHSL1102A",
    registrationCount: 35,
    completedProjects: 30,
    ongoingProjects: 4,
    delayedProjects: 1,
    averageDelayMonths: 2,
    trustScore: 96,
    state: "Maharashtra"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4d10",
    builderName: "DLF Limited",
    panNumber: "ADLFL5521H",
    registrationCount: 50,
    completedProjects: 44,
    ongoingProjects: 5,
    delayedProjects: 1,
    averageDelayMonths: 3,
    trustScore: 95,
    state: "Gujarat"
  }
];

const reraProjects = [
  {
    _id: "60c72b2f9b1d8b2a3c8e4e01",
    projectName: "Adani Shantigram Water Lily",
    registrationNumber: "PR/GJ/AHMEDABAD/SANAND/AUDA/RAA00045/050917",
    state: "Gujarat",
    builderName: "Adani Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d01",
    completionStatus: "Completed",
    registrationDate: new Date("2017-09-05"),
    completionDate: new Date("2021-06-30"),
    originalCompletionDate: new Date("2020-12-31"),
    legalApprovals: ["GUCDA Approval", "Fire NOC", "Structural Stability Certificate", "Environmental Clearance"],
    delayedMonths: 6,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Shantigram",
    city: "Ahmedabad",
    totalAreaSqm: 84500,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e02",
    projectName: "Maple Tree Garden Homes",
    registrationNumber: "PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA00289/280917",
    state: "Gujarat",
    builderName: "Ganesh Housing",
    builderId: "60c72b2f9b1d8b2a3c8e4d02",
    completionStatus: "Completed",
    registrationDate: new Date("2017-09-28"),
    completionDate: new Date("2021-03-31"),
    originalCompletionDate: new Date("2021-03-31"),
    legalApprovals: ["AMC Building Plan Permission", "Fire Safety NOC", "BU Permission"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Thaltej",
    city: "Ahmedabad",
    totalAreaSqm: 42000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e03",
    projectName: "Lodha World Towers",
    registrationNumber: "P51900008345",
    state: "Maharashtra",
    builderName: "Lodha Group",
    builderId: "60c72b2f9b1d8b2a3c8e4d03",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-10"),
    completionDate: new Date("2022-12-31"),
    originalCompletionDate: new Date("2021-12-31"),
    legalApprovals: ["MCGM Building Proposal Approval", "MoEF Environmental Clearance", "Aviation Height Clearance NOC"],
    delayedMonths: 12,
    legalDisputeFlags: true,
    disputeDetails: "NOC issues with neighboring municipal layout resolved in late 2021.",
    locality: "Lower Parel",
    city: "Mumbai",
    totalAreaSqm: 125000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e04",
    projectName: "Godrej Emerald",
    registrationNumber: "P51700000120",
    state: "Maharashtra",
    builderName: "Godrej Properties",
    builderId: "60c72b2f9b1d8b2a3c8e4d04",
    completionStatus: "Ongoing",
    registrationDate: new Date("2018-02-15"),
    originalCompletionDate: new Date("2026-12-31"),
    legalApprovals: ["TMC Commencment Certificate", "Pollution Control Board Consent", "Tree Authority Approval"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Ghodbunder Road",
    city: "Mumbai",
    totalAreaSqm: 95000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e05",
    projectName: "Life Republic Sector R10",
    registrationNumber: "P52100026453",
    state: "Maharashtra",
    builderName: "Kolte-Patil Developers",
    builderId: "60c72b2f9b1d8b2a3c8e4d05",
    completionStatus: "Delayed",
    registrationDate: new Date("2020-05-12"),
    originalCompletionDate: new Date("2025-06-30"),
    legalApprovals: ["PMRDA Approvals", "Water NOC", "Fire Clearance"],
    delayedMonths: 13,
    legalDisputeFlags: true,
    disputeDetails: "Pending environmental report compliance hearing at NGT.",
    locality: "Hinjewadi",
    city: "Pune",
    totalAreaSqm: 68000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e06",
    projectName: "Rajhans Elanza",
    registrationNumber: "PR/GJ/SURAT/SURAT CITY/SUDA/MAA00234/121017",
    state: "Gujarat",
    builderName: "Rajhans Group",
    builderId: "60c72b2f9b1d8b2a3c8e4d06",
    completionStatus: "Completed",
    registrationDate: new Date("2017-10-12"),
    completionDate: new Date("2022-03-31"),
    originalCompletionDate: new Date("2021-09-30"),
    legalApprovals: ["SMC Commercial Plan Consent", "Fire NOC Certificate"],
    delayedMonths: 6,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Vesu",
    city: "Surat",
    totalAreaSqm: 38000,
    projectType: "Commercial"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e07",
    projectName: "Sunteck Beach Residences",
    registrationNumber: "P51900032900",
    state: "Maharashtra",
    builderName: "Sunteck Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d07",
    completionStatus: "Ongoing",
    registrationDate: new Date("2021-08-01"),
    originalCompletionDate: new Date("2027-12-31"),
    legalApprovals: ["CRZ Clearance", "VVCMC Approvals", "Aviation Safety Cert"],
    delayedMonths: 18,
    legalDisputeFlags: true,
    disputeDetails: "Environmental petition regarding mangrove buffer zone boundary alignment.",
    locality: "Vasai",
    city: "Mumbai",
    totalAreaSqm: 112000,
    projectType: "Mixed"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e08",
    projectName: "L&T Emerald Isle",
    registrationNumber: "P51800000223",
    state: "Maharashtra",
    builderName: "L&T Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d08",
    completionStatus: "Completed",
    registrationDate: new Date("2018-05-10"),
    completionDate: new Date("2022-12-31"),
    originalCompletionDate: new Date("2022-12-31"),
    legalApprovals: ["MCGM Building Plan", "Fire NOC", "Pollution Clearance"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Powai",
    city: "Mumbai",
    totalAreaSqm: 105000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e09",
    projectName: "Tata Serein",
    registrationNumber: "P51700000152",
    state: "Maharashtra",
    builderName: "Tata Housing",
    builderId: "60c72b2f9b1d8b2a3c8e4d09",
    completionStatus: "Completed",
    registrationDate: new Date("2017-09-12"),
    completionDate: new Date("2021-10-30"),
    originalCompletionDate: new Date("2021-06-30"),
    legalApprovals: ["TMC Occupancy Certificate", "Fire Safety NOC", "BU Permission"],
    delayedMonths: 4,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Pokhran Road",
    city: "Mumbai",
    totalAreaSqm: 88000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e10",
    projectName: "DLF Cybercity Ahmedabad",
    registrationNumber: "PR/GJ/AHMEDABAD/CITY/AUDA/CAA00099/101018",
    state: "Gujarat",
    builderName: "DLF Limited",
    builderId: "60c72b2f9b1d8b2a3c8e4d10",
    completionStatus: "Ongoing",
    registrationDate: new Date("2018-10-10"),
    originalCompletionDate: new Date("2027-12-31"),
    legalApprovals: ["AMC Commercial Approvals", "Environmental Clearance", "Aviation Height NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Sarkhej-Gandhinagar Highway",
    city: "Ahmedabad",
    totalAreaSqm: 150000,
    projectType: "Commercial"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e11",
    projectName: "Adani Astra",
    registrationNumber: "PR/GJ/AHMEDABAD/CITY/AUDA/RAA00078/120917",
    state: "Gujarat",
    builderName: "Adani Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d01",
    completionStatus: "Completed",
    registrationDate: new Date("2017-09-12"),
    completionDate: new Date("2021-08-31"),
    originalCompletionDate: new Date("2021-03-31"),
    legalApprovals: ["AMC BU Permission", "Fire NOC", "Aviation NOC"],
    delayedMonths: 5,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Jagatpur",
    city: "Ahmedabad",
    totalAreaSqm: 56000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e12",
    projectName: "Ganesh Maple Tree Phase 2",
    registrationNumber: "PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA00412/101017",
    state: "Gujarat",
    builderName: "Ganesh Housing",
    builderId: "60c72b2f9b1d8b2a3c8e4d02",
    completionStatus: "Ongoing",
    registrationDate: new Date("2017-10-10"),
    originalCompletionDate: new Date("2026-12-31"),
    legalApprovals: ["AMC Plan Approval", "Fire NOC", "Environmental Clearance"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Thaltej",
    city: "Ahmedabad",
    totalAreaSqm: 48000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e13",
    projectName: "Lodha Bellissimo",
    registrationNumber: "P51900008891",
    state: "Maharashtra",
    builderName: "Lodha Group",
    builderId: "60c72b2f9b1d8b2a3c8e4d03",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-15"),
    completionDate: new Date("2020-12-31"),
    originalCompletionDate: new Date("2020-06-30"),
    legalApprovals: ["MCGM BU Permission", "Fire Safety NOC", "Lift NOC"],
    delayedMonths: 6,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Mahalaxmi",
    city: "Mumbai",
    totalAreaSqm: 92000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e14",
    projectName: "Godrej Woods",
    registrationNumber: "P51700001024",
    state: "Maharashtra",
    builderName: "Godrej Properties",
    builderId: "60c72b2f9b1d8b2a3c8e4d04",
    completionStatus: "Ongoing",
    registrationDate: new Date("2019-04-12"),
    originalCompletionDate: new Date("2027-06-30"),
    legalApprovals: ["NMMC Commencement Cert", "Tree Authority NOC", "CFO NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Vashi",
    city: "Mumbai",
    totalAreaSqm: 74000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e15",
    projectName: "Life Republic Sector R3",
    registrationNumber: "P52100021495",
    state: "Maharashtra",
    builderName: "Kolte-Patil Developers",
    builderId: "60c72b2f9b1d8b2a3c8e4d05",
    completionStatus: "Ongoing",
    registrationDate: new Date("2019-11-20"),
    originalCompletionDate: new Date("2026-12-31"),
    legalApprovals: ["PMRDA CC", "Environmental Clearance", "MSEDCL Water NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Hinjewadi",
    city: "Pune",
    totalAreaSqm: 110000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e16",
    projectName: "Rajhans Royal",
    registrationNumber: "PR/GJ/SURAT/SURAT CITY/SUDA/MAA00122/150917",
    state: "Gujarat",
    builderName: "Rajhans Group",
    builderId: "60c72b2f9b1d8b2a3c8e4d06",
    completionStatus: "Completed",
    registrationDate: new Date("2017-09-15"),
    completionDate: new Date("2021-03-31"),
    originalCompletionDate: new Date("2020-09-30"),
    legalApprovals: ["SMC BU Permission", "Fire Safety NOC", "Structural Stability Certificate"],
    delayedMonths: 6,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Vesu",
    city: "Surat",
    totalAreaSqm: 42000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e17",
    projectName: "Sunteck City Avenue",
    registrationNumber: "P51800004921",
    state: "Maharashtra",
    builderName: "Sunteck Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d07",
    completionStatus: "Completed",
    registrationDate: new Date("2017-09-01"),
    completionDate: new Date("2021-12-31"),
    originalCompletionDate: new Date("2020-12-31"),
    legalApprovals: ["MCGM Occ Cert", "Fire NOC", "Aviation Clearance"],
    delayedMonths: 12,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Goregaon West",
    city: "Mumbai",
    totalAreaSqm: 88000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e18",
    projectName: "L&T Crescent Bay",
    registrationNumber: "P51900000402",
    state: "Maharashtra",
    builderName: "L&T Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d08",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-05"),
    completionDate: new Date("2021-06-30"),
    originalCompletionDate: new Date("2021-06-30"),
    legalApprovals: ["MCGM Occupation Cert", "Fire NOC", "Environmental Board Clearance"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Parel",
    city: "Mumbai",
    totalAreaSqm: 135000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e19",
    projectName: "Tata Tritvam",
    registrationNumber: "P51800000994",
    state: "Maharashtra",
    builderName: "Tata Housing",
    builderId: "60c72b2f9b1d8b2a3c8e4d09",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-25"),
    completionDate: new Date("2020-12-31"),
    originalCompletionDate: new Date("2020-12-31"),
    legalApprovals: ["MCGM BU Permission", "Fire NOC", "Tree Authority NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Mulund",
    city: "Mumbai",
    totalAreaSqm: 95000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e20",
    projectName: "DLF Cybercity Phase 2",
    registrationNumber: "PR/GJ/AHMEDABAD/CITY/AUDA/CAA00104/151119",
    state: "Gujarat",
    builderName: "DLF Limited",
    builderId: "60c72b2f9b1d8b2a3c8e4d10",
    completionStatus: "Ongoing",
    registrationDate: new Date("2019-11-15"),
    originalCompletionDate: new Date("2028-12-31"),
    legalApprovals: ["AMC Building Permit", "Pollution Board Consent", "Airport height NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Sarkhej-Gandhinagar Highway",
    city: "Ahmedabad",
    totalAreaSqm: 180000,
    projectType: "Commercial"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e21",
    projectName: "Adani The Views",
    registrationNumber: "P51900021482",
    state: "Maharashtra",
    builderName: "Adani Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d01",
    completionStatus: "Ongoing",
    registrationDate: new Date("2019-09-10"),
    originalCompletionDate: new Date("2026-12-31"),
    legalApprovals: ["MCGM CC", "Coastal Zone NOC", "Fire Clearance"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Ghatkopar East",
    city: "Mumbai",
    totalAreaSqm: 68000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e22",
    projectName: "Ganesh Genesis",
    registrationNumber: "PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA00014/180817",
    state: "Gujarat",
    builderName: "Ganesh Housing",
    builderId: "60c72b2f9b1d8b2a3c8e4d02",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-18"),
    completionDate: new Date("2020-09-30"),
    originalCompletionDate: new Date("2020-09-30"),
    legalApprovals: ["AMC BU Permission", "Fire Safety NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Gota",
    city: "Ahmedabad",
    totalAreaSqm: 39000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e23",
    projectName: "Lodha Park",
    registrationNumber: "P51900001339",
    state: "Maharashtra",
    builderName: "Lodha Group",
    builderId: "60c72b2f9b1d8b2a3c8e4d03",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-01"),
    completionDate: new Date("2021-03-31"),
    originalCompletionDate: new Date("2020-03-31"),
    legalApprovals: ["MCGM Occupation Cert", "MoEF Consent", "CFO NOC"],
    delayedMonths: 12,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Worli",
    city: "Mumbai",
    totalAreaSqm: 145000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e24",
    projectName: "Godrej Riverhills",
    registrationNumber: "P52100022410",
    state: "Maharashtra",
    builderName: "Godrej Properties",
    builderId: "60c72b2f9b1d8b2a3c8e4d04",
    completionStatus: "Ongoing",
    registrationDate: new Date("2020-02-15"),
    originalCompletionDate: new Date("2027-12-31"),
    legalApprovals: ["PMRDA CC Plan", "Environmental Consent", "Fire NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Mahalunge",
    city: "Pune",
    totalAreaSqm: 82000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e25",
    projectName: "Kolte-Patil Western Avenue",
    registrationNumber: "P52100000941",
    state: "Maharashtra",
    builderName: "Kolte-Patil Developers",
    builderId: "60c72b2f9b1d8b2a3c8e4d05",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-10"),
    completionDate: new Date("2020-06-30"),
    originalCompletionDate: new Date("2019-12-31"),
    legalApprovals: ["PCMC Occupation Cert", "Fire NOC", "BU Consent"],
    delayedMonths: 6,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Wakad",
    city: "Pune",
    totalAreaSqm: 63000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e26",
    projectName: "Rajhans Synfonia",
    registrationNumber: "PR/GJ/SURAT/SURAT CITY/SUDA/MAA00451/221017",
    state: "Gujarat",
    builderName: "Rajhans Group",
    builderId: "60c72b2f9b1d8b2a3c8e4d06",
    completionStatus: "Ongoing",
    registrationDate: new Date("2017-10-22"),
    originalCompletionDate: new Date("2026-12-31"),
    legalApprovals: ["SMC Plan Consent", "Fire NOC"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Adajan",
    city: "Surat",
    totalAreaSqm: 51000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e27",
    projectName: "Sunteck Signia High",
    registrationNumber: "P51800009210",
    state: "Maharashtra",
    builderName: "Sunteck Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d07",
    completionStatus: "Completed",
    registrationDate: new Date("2017-08-28"),
    completionDate: new Date("2021-03-31"),
    originalCompletionDate: new Date("2020-03-31"),
    legalApprovals: ["MCGM BU Permission", "Fire NOC", "Structural NOC"],
    delayedMonths: 12,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Borivali East",
    city: "Mumbai",
    totalAreaSqm: 49000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e28",
    projectName: "L&T Seawoods Residences",
    registrationNumber: "P51700021490",
    state: "Maharashtra",
    builderName: "L&T Realty",
    builderId: "60c72b2f9b1d8b2a3c8e4d08",
    completionStatus: "Ongoing",
    registrationDate: new Date("2019-08-10"),
    originalCompletionDate: new Date("2026-12-31"),
    legalApprovals: ["CIDCO CC Plan", "Tree NOC", "Fire Clearance"],
    delayedMonths: 0,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Seawoods",
    city: "Mumbai",
    totalAreaSqm: 115000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e29",
    projectName: "Tata Aveza",
    registrationNumber: "P51800001099",
    state: "Maharashtra",
    builderName: "Tata Housing",
    builderId: "60c72b2f9b1d8b2a3c8e4d09",
    completionStatus: "Ongoing",
    registrationDate: new Date("2017-09-02"),
    originalCompletionDate: new Date("2027-06-30"),
    legalApprovals: ["MCGM Plan Approval", "Tree Authority Clearance", "CFO NOC"],
    delayedMonths: 0,
    legalDisputeFlags: true,
    disputeDetails: "Pending clearance clarification from municipal land survey office regarding layout border.",
    locality: "Mulund East",
    city: "Mumbai",
    totalAreaSqm: 108000,
    projectType: "Residential"
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4e30",
    projectName: "DLF Garden City",
    registrationNumber: "PR/GJ/AHMEDABAD/SANAND/AUDA/RAA00299/181017",
    state: "Gujarat",
    builderName: "DLF Limited",
    builderId: "60c72b2f9b1d8b2a3c8e4d10",
    completionStatus: "Completed",
    registrationDate: new Date("2017-10-18"),
    completionDate: new Date("2021-06-30"),
    originalCompletionDate: new Date("2020-12-31"),
    legalApprovals: ["AUDA BU Permission", "Fire Safety Certificate"],
    delayedMonths: 6,
    legalDisputeFlags: false,
    disputeDetails: "",
    locality: "Sanand",
    city: "Ahmedabad",
    totalAreaSqm: 120000,
    projectType: "Residential"
  }
];

const landRecords = [
  {
    _id: "60c72b2f9b1d8b2a3c8e4f01",
    surveyNumber: "142/A",
    state: "Gujarat",
    district: "Ahmedabad",
    taluka: "Daskroi",
    village: "Jetalpur",
    ownerName: "Ganesh Housing Corporation Ltd",
    landCategory: "Non-Agricultural (NA)",
    areaHectares: 4.82,
    mutationHistory: [
      {
        mutationNumber: "M-4829",
        date: new Date("2021-11-12"),
        buyer: "Ganesh Housing Corporation Ltd",
        seller: "Ramanbhai Patel & Sons",
        mutationType: "Sale",
        remarks: "Converted to NA residential vide order no. NA-RES-40291"
      },
      {
        mutationNumber: "M-2294",
        date: new Date("2015-04-18"),
        buyer: "Ramanbhai Patel",
        seller: "Haribhai Patel",
        mutationType: "Inheritance",
        remarks: "Family property partitioning"
      }
    ],
    governmentRestrictions: ["None"]
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4f02",
    surveyNumber: "228/1",
    state: "Gujarat",
    district: "Surat",
    taluka: "Choryasi",
    village: "Dumas",
    ownerName: "Kantibhai Somabhai Ahir",
    landCategory: "Agricultural",
    areaHectares: 12.4,
    mutationHistory: [
      {
        mutationNumber: "M-9801",
        date: new Date("2018-09-02"),
        buyer: "Kantibhai Somabhai Ahir",
        seller: "Amrutlal Mehta",
        mutationType: "Sale",
        remarks: "Deed value verified at sub-registrar office"
      }
    ],
    governmentRestrictions: ["CRZ-II Zone Boundary (Coastal restriction)"]
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4f03",
    surveyNumber: "89/5",
    state: "Maharashtra",
    district: "Pune",
    taluka: "Mulshi",
    village: "Maan",
    ownerName: "Kolte-Patil Infrastructure Ltd",
    landCategory: "Non-Agricultural (NA)",
    areaHectares: 8.15,
    mutationHistory: [
      {
        mutationNumber: "PM-12948",
        date: new Date("2022-01-20"),
        buyer: "Kolte-Patil Infrastructure Ltd",
        seller: "Vasantrao Kadu & Others",
        mutationType: "Sale",
        remarks: "PMRDA NA permit verified"
      }
    ],
    governmentRestrictions: ["None"]
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4f04",
    surveyNumber: "302/B",
    state: "Maharashtra",
    district: "Thane",
    taluka: "Kalyan",
    village: "Dombivli",
    ownerName: "Private Individual (Masked)",
    landCategory: "Agricultural",
    areaHectares: 2.1,
    mutationHistory: [
      {
        mutationNumber: "TH-4029",
        date: new Date("2024-03-05"),
        buyer: "Private Individual",
        seller: "Balasaheb Patil",
        mutationType: "Mortgage",
        remarks: "Hypothecated to HDFC Bank Ltd for INR 4.5 Crores"
      }
    ],
    governmentRestrictions: ["Forest Buffer Zone (100m limitation)"]
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4f05",
    surveyNumber: "512/3",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    taluka: "Kurla",
    village: "Powai",
    ownerName: "L&T Realty Private Limited",
    landCategory: "Non-Agricultural (NA)",
    areaHectares: 6.25,
    mutationHistory: [
      {
        mutationNumber: "MU-POW-4902",
        date: new Date("2020-08-15"),
        buyer: "L&T Realty Private Limited",
        seller: "Industrialists Cooperative Society",
        mutationType: "Sale",
        remarks: "Approved for high-density IT/Commercial mixed layout development"
      }
    ],
    governmentRestrictions: ["None"]
  },
  {
    _id: "60c72b2f9b1d8b2a3c8e4f06",
    surveyNumber: "94/B",
    state: "Gujarat",
    district: "Ahmedabad",
    taluka: "Sanand",
    village: "Sarkhej",
    ownerName: "DLF Cyber City Developers Ltd",
    landCategory: "Non-Agricultural (NA)",
    areaHectares: 15.45,
    mutationHistory: [
      {
        mutationNumber: "AM-SARK-10294",
        date: new Date("2021-03-22"),
        buyer: "DLF Cyber City Developers Ltd",
        seller: "Gujarat Industrial Development Corporation",
        mutationType: "Allotment",
        remarks: "GIDC Industrial-to-Commercial change of land use approved"
      }
    ],
    governmentRestrictions: ["High-Tension Power Grid Line easement path border"]
  }
];

const propertyTransactions = [
  // Ahmedabad - Thaltej
  {
    deedNumber: "AMD/THAL/2025/1194",
    deedDate: new Date("2025-05-14"),
    state: "Gujarat",
    district: "Ahmedabad",
    city: "Ahmedabad",
    locality: "Thaltej",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 185,
    transactionAmountINR: 17500000, // 1.75 Cr
    calculatedRatePerSqm: 94594,
    circleRatePerSqm: 82000,
    variancePercentage: 15.3,
    buyerName: "Nirav Shah",
    sellerName: "Dinesh Patel"
  },
  {
    deedNumber: "AMD/THAL/2025/2249",
    deedDate: new Date("2025-06-18"),
    state: "Gujarat",
    district: "Ahmedabad",
    city: "Ahmedabad",
    locality: "Thaltej",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 220,
    transactionAmountINR: 21500000, // 2.15 Cr
    calculatedRatePerSqm: 97727,
    circleRatePerSqm: 82000,
    variancePercentage: 19.1,
    buyerName: "Amitabh Shah",
    sellerName: "Bhargav Mehta"
  },
  // Mumbai - Lower Parel
  {
    deedNumber: "MUM/LP/2025/4491",
    deedDate: new Date("2025-04-02"),
    state: "Maharashtra",
    district: "Mumbai City",
    city: "Mumbai",
    locality: "Lower Parel",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 120,
    transactionAmountINR: 42000000, // 4.2 Cr
    calculatedRatePerSqm: 350000,
    circleRatePerSqm: 310000,
    variancePercentage: 12.9,
    buyerName: "Siddharth Malhotra",
    sellerName: "Karan Johar"
  },
  {
    deedNumber: "MUM/LP/2025/0821",
    deedDate: new Date("2025-06-25"),
    state: "Maharashtra",
    district: "Mumbai City",
    city: "Mumbai",
    locality: "Lower Parel",
    propertyType: "Commercial Office",
    builtUpAreaSqm: 450,
    transactionAmountINR: 192000000, // 19.2 Cr
    calculatedRatePerSqm: 426666,
    circleRatePerSqm: 350000,
    variancePercentage: 21.9,
    buyerName: "Alpha Capital Advisers",
    sellerName: "Lodha Developers"
  },
  // Underpriced Transaction Anomaly for Fraud Detection
  {
    deedNumber: "MUM/LP/2025/1102",
    deedDate: new Date("2025-06-28"),
    state: "Maharashtra",
    district: "Mumbai City",
    city: "Mumbai",
    locality: "Lower Parel",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 110,
    transactionAmountINR: 22000000, // 2.2 Cr (Under circle rate of 3.41 Cr!)
    calculatedRatePerSqm: 200000,
    circleRatePerSqm: 310000,
    variancePercentage: -35.48,
    buyerName: "Gopal Mandhan",
    sellerName: "Ramesh Aggarwal"
  },
  // Pune - Hinjewadi
  {
    deedNumber: "PUN/HINJ/2025/5529",
    deedDate: new Date("2025-05-22"),
    state: "Maharashtra",
    district: "Pune",
    city: "Pune",
    locality: "Hinjewadi",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 95,
    transactionAmountINR: 7500000,
    calculatedRatePerSqm: 78947,
    circleRatePerSqm: 72000,
    variancePercentage: 9.6,
    buyerName: "Rahul Sharma",
    sellerName: "Sanjay Deshmukh"
  },
  {
    deedNumber: "MUM/POW/2025/2290",
    deedDate: new Date("2025-05-20"),
    state: "Maharashtra",
    district: "Mumbai Suburban",
    city: "Mumbai",
    locality: "Powai",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 140,
    transactionAmountINR: 32000000,
    calculatedRatePerSqm: 228571,
    circleRatePerSqm: 210000,
    variancePercentage: 8.8,
    buyerName: "Rajesh Sharma",
    sellerName: "L&T Developers"
  },
  {
    deedNumber: "MUM/WOR/2025/1049",
    deedDate: new Date("2025-06-15"),
    state: "Maharashtra",
    district: "Mumbai City",
    city: "Mumbai",
    locality: "Worli",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 200,
    transactionAmountINR: 90000000,
    calculatedRatePerSqm: 450000,
    circleRatePerSqm: 380000,
    variancePercentage: 18.4,
    buyerName: "Deepak Parekh",
    sellerName: "Lodha Group"
  },
  {
    deedNumber: "AMD/SGH/2025/0981",
    deedDate: new Date("2025-04-18"),
    state: "Gujarat",
    district: "Ahmedabad",
    city: "Ahmedabad",
    locality: "Sarkhej-Gandhinagar Highway",
    propertyType: "Commercial Office",
    builtUpAreaSqm: 350,
    transactionAmountINR: 28000000,
    calculatedRatePerSqm: 80000,
    circleRatePerSqm: 72000,
    variancePercentage: 11.1,
    buyerName: "Tech Solutions Pvt Ltd",
    sellerName: "DLF Limited"
  },
  {
    deedNumber: "PUN/WAK/2025/1104",
    deedDate: new Date("2025-05-11"),
    state: "Maharashtra",
    district: "Pune",
    city: "Pune",
    locality: "Wakad",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 120,
    transactionAmountINR: 9200000,
    calculatedRatePerSqm: 76666,
    circleRatePerSqm: 68000,
    variancePercentage: 12.7,
    buyerName: "Sachin Kulkarni",
    sellerName: "Kolte-Patil Developers"
  },
  {
    deedNumber: "SUR/ADA/2025/0824",
    deedDate: new Date("2025-06-02"),
    state: "Gujarat",
    district: "Surat",
    city: "Surat",
    locality: "Adajan",
    propertyType: "Residential Apartment",
    builtUpAreaSqm: 150,
    transactionAmountINR: 8500000,
    calculatedRatePerSqm: 56666,
    circleRatePerSqm: 52000,
    variancePercentage: 9.0,
    buyerName: "Alpesh Patel",
    sellerName: "Rajhans Group"
  }
];

const areaAnalytics = [
  {
    city: "Ahmedabad",
    locality: "Thaltej",
    state: "Gujarat",
    averageMarketRatePerSqm: 96000,
    averageCircleRatePerSqm: 82000,
    growthScore: 88,
    demandTrend: "High",
    infrastructureImpactScore: 85,
    populationDensityPerSqKm: 14200,
    householdIncomeTier: "High",
    metroProximityKm: 1.2,
    highwayProximityKm: 0.5,
    airportProximityKm: 14.5,
    commercialDensityScore: 82
  },
  {
    city: "Ahmedabad",
    locality: "Science City",
    state: "Gujarat",
    averageMarketRatePerSqm: 89000,
    averageCircleRatePerSqm: 74000,
    growthScore: 92,
    demandTrend: "High",
    infrastructureImpactScore: 95,
    populationDensityPerSqKm: 9800,
    householdIncomeTier: "Upper-Middle",
    metroProximityKm: 2.1,
    highwayProximityKm: 1.5,
    airportProximityKm: 16.0,
    commercialDensityScore: 78
  },
  {
    city: "Mumbai",
    locality: "Lower Parel",
    state: "Maharashtra",
    averageMarketRatePerSqm: 365000,
    averageCircleRatePerSqm: 310000,
    growthScore: 82,
    demandTrend: "High",
    infrastructureImpactScore: 80,
    populationDensityPerSqKm: 28500,
    householdIncomeTier: "High",
    metroProximityKm: 0.2,
    highwayProximityKm: 3.5,
    airportProximityKm: 11.2,
    commercialDensityScore: 98
  },
  {
    city: "Mumbai",
    locality: "Thane West",
    state: "Maharashtra",
    averageMarketRatePerSqm: 185000,
    averageCircleRatePerSqm: 155000,
    growthScore: 89,
    demandTrend: "High",
    infrastructureImpactScore: 92,
    populationDensityPerSqKm: 21000,
    householdIncomeTier: "Upper-Middle",
    metroProximityKm: 0.8,
    highwayProximityKm: 0.2,
    airportProximityKm: 24.0,
    commercialDensityScore: 85
  },
  {
    city: "Pune",
    locality: "Hinjewadi",
    state: "Maharashtra",
    averageMarketRatePerSqm: 79000,
    averageCircleRatePerSqm: 72000,
    growthScore: 84,
    demandTrend: "Moderate",
    infrastructureImpactScore: 88,
    populationDensityPerSqKm: 8500,
    householdIncomeTier: "Middle",
    metroProximityKm: 0.5, // Pune metro under construction
    highwayProximityKm: 1.0,
    airportProximityKm: 26.0,
    commercialDensityScore: 90
  },
  {
    city: "Surat",
    locality: "Vesu",
    state: "Gujarat",
    averageMarketRatePerSqm: 68000,
    averageCircleRatePerSqm: 58000,
    growthScore: 86,
    demandTrend: "High",
    infrastructureImpactScore: 82,
    populationDensityPerSqKm: 11200,
    householdIncomeTier: "Upper-Middle",
    metroProximityKm: 1.5,
    highwayProximityKm: 3.0,
    airportProximityKm: 6.5,
    commercialDensityScore: 74
  },
  {
    city: "Mumbai",
    locality: "Powai",
    state: "Maharashtra",
    averageMarketRatePerSqm: 230000,
    averageCircleRatePerSqm: 210000,
    growthScore: 90,
    demandTrend: "High",
    infrastructureImpactScore: 92,
    populationDensityPerSqKm: 19500,
    householdIncomeTier: "High",
    metroProximityKm: 0.5,
    highwayProximityKm: 1.2,
    airportProximityKm: 6.8,
    commercialDensityScore: 92
  },
  {
    city: "Mumbai",
    locality: "Worli",
    state: "Maharashtra",
    averageMarketRatePerSqm: 460000,
    averageCircleRatePerSqm: 380000,
    growthScore: 85,
    demandTrend: "High",
    infrastructureImpactScore: 82,
    populationDensityPerSqKm: 24500,
    householdIncomeTier: "High",
    metroProximityKm: 1.0,
    highwayProximityKm: 5.0,
    airportProximityKm: 15.0,
    commercialDensityScore: 95
  },
  {
    city: "Ahmedabad",
    locality: "Sarkhej-Gandhinagar Highway",
    state: "Gujarat",
    averageMarketRatePerSqm: 82000,
    averageCircleRatePerSqm: 72000,
    growthScore: 94,
    demandTrend: "High",
    infrastructureImpactScore: 96,
    populationDensityPerSqKm: 8200,
    householdIncomeTier: "Upper-Middle",
    metroProximityKm: 0.8,
    highwayProximityKm: 0.1,
    airportProximityKm: 18.0,
    commercialDensityScore: 88
  },
  {
    city: "Pune",
    locality: "Wakad",
    state: "Maharashtra",
    averageMarketRatePerSqm: 78000,
    averageCircleRatePerSqm: 68000,
    growthScore: 87,
    demandTrend: "High",
    infrastructureImpactScore: 89,
    populationDensityPerSqKm: 11500,
    householdIncomeTier: "Upper-Middle",
    metroProximityKm: 1.8,
    highwayProximityKm: 0.5,
    airportProximityKm: 22.0,
    commercialDensityScore: 78
  },
  {
    city: "Surat",
    locality: "Adajan",
    state: "Gujarat",
    averageMarketRatePerSqm: 58000,
    averageCircleRatePerSqm: 52000,
    growthScore: 82,
    demandTrend: "Moderate",
    infrastructureImpactScore: 78,
    populationDensityPerSqKm: 13500,
    householdIncomeTier: "Middle",
    metroProximityKm: 2.5,
    highwayProximityKm: 2.0,
    airportProximityKm: 10.5,
    commercialDensityScore: 70
  },
  {
    city: "Mumbai",
    locality: "Pokhran Road",
    state: "Maharashtra",
    averageMarketRatePerSqm: 168000,
    averageCircleRatePerSqm: 148000,
    growthScore: 86,
    demandTrend: "High",
    infrastructureImpactScore: 85,
    populationDensityPerSqKm: 18200,
    householdIncomeTier: "Upper-Middle",
    metroProximityKm: 1.5,
    highwayProximityKm: 0.8,
    airportProximityKm: 26.0,
    commercialDensityScore: 80
  }
];

const infrastructureProjects = [
  {
    projectName: "Ahmedabad Metro Phase 2 Link",
    projectType: "Metro Line",
    city: "Ahmedabad",
    state: "Gujarat",
    status: "Under Construction",
    expectedCompletionYear: 2027,
    estimatedCostINR_Crores: 5384,
    impactRadiusKm: 3,
    affectedLocalities: ["GIFT City", "Koba Circle", "Motera", "Gandhinagar Sector 21"],
    description: "Extending metro connectivity from Motera Stadium northwards to GIFT City and Gandhinagar, directly boosting real estate corridors."
  },
  {
    projectName: "Mumbai Metro Line 4 (Wadala-Ghatkopar-Thane)",
    projectType: "Metro Line",
    city: "Mumbai",
    state: "Maharashtra",
    status: "Under Construction",
    expectedCompletionYear: 2027,
    estimatedCostINR_Crores: 14549,
    impactRadiusKm: 2.5,
    affectedLocalities: ["Ghodbunder Road", "Thane West", "Mulund", "Kanjurmarg", "Wadala"],
    description: "32.3 km elevated corridor aimed at reducing travel time from Thane to Central Mumbai, driving massive residential interest."
  },
  {
    projectName: "Navi Mumbai International Airport (NMIAL)",
    projectType: "Airport",
    city: "Mumbai",
    state: "Maharashtra",
    status: "Under Construction",
    expectedCompletionYear: 2026,
    estimatedCostINR_Crores: 16700,
    impactRadiusKm: 15,
    affectedLocalities: ["Kharghar", "Panvel", "Ulwe", "Kamothe", "Belapur"],
    description: "The greenfield secondary international airport for Mumbai area. Major price appreciation catalyst for Navi Mumbai and Raigad districts."
  },
  {
    projectName: "Ahmedabad-Dholera Expressway",
    projectType: "Expressway",
    city: "Ahmedabad",
    state: "Gujarat",
    status: "Under Construction",
    expectedCompletionYear: 2026,
    estimatedCostINR_Crores: 4000,
    impactRadiusKm: 10,
    affectedLocalities: ["Sarkhej", "Dholera SIR", "Vataman"],
    description: "4-lane access-controlled highway linking Ahmedabad to the Dholera Special Investment Region (SIR) industrial corridor."
  }
];

const historicalMarketData = [
  // Ahmedabad - Thaltej
  { city: "Ahmedabad", locality: "Thaltej", year: 2021, quarter: "Q1", averagePricePerSqm: 72000, transactionVolume: 142, newLaunchCount: 2 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2021, quarter: "Q3", averagePricePerSqm: 74000, transactionVolume: 130, newLaunchCount: 1 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2022, quarter: "Q1", averagePricePerSqm: 78000, transactionVolume: 165, newLaunchCount: 3 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2022, quarter: "Q3", averagePricePerSqm: 80500, transactionVolume: 154, newLaunchCount: 2 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2023, quarter: "Q1", averagePricePerSqm: 85000, transactionVolume: 198, newLaunchCount: 4 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2023, quarter: "Q3", averagePricePerSqm: 88000, transactionVolume: 172, newLaunchCount: 1 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2024, quarter: "Q1", averagePricePerSqm: 91500, transactionVolume: 220, newLaunchCount: 5 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2024, quarter: "Q3", averagePricePerSqm: 93800, transactionVolume: 190, newLaunchCount: 2 },
  { city: "Ahmedabad", locality: "Thaltej", year: 2025, quarter: "Q1", averagePricePerSqm: 95500, transactionVolume: 242, newLaunchCount: 3 },

  // Mumbai - Lower Parel
  { city: "Mumbai", locality: "Lower Parel", year: 2021, quarter: "Q1", averagePricePerSqm: 295000, transactionVolume: 85, newLaunchCount: 1 },
  { city: "Mumbai", locality: "Lower Parel", year: 2021, quarter: "Q3", averagePricePerSqm: 302000, transactionVolume: 92, newLaunchCount: 0 },
  { city: "Mumbai", locality: "Lower Parel", year: 2022, quarter: "Q1", averagePricePerSqm: 315000, transactionVolume: 110, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Lower Parel", year: 2022, quarter: "Q3", averagePricePerSqm: 322000, transactionVolume: 104, newLaunchCount: 1 },
  { city: "Mumbai", locality: "Lower Parel", year: 2023, quarter: "Q1", averagePricePerSqm: 335000, transactionVolume: 130, newLaunchCount: 3 },
  { city: "Mumbai", locality: "Lower Parel", year: 2023, quarter: "Q3", averagePricePerSqm: 341000, transactionVolume: 118, newLaunchCount: 0 },
  { city: "Mumbai", locality: "Lower Parel", year: 2024, quarter: "Q1", averagePricePerSqm: 350000, transactionVolume: 148, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Lower Parel", year: 2024, quarter: "Q3", averagePricePerSqm: 358000, transactionVolume: 122, newLaunchCount: 1 },
  { city: "Mumbai", locality: "Lower Parel", year: 2025, quarter: "Q1", averagePricePerSqm: 362000, transactionVolume: 155, newLaunchCount: 2 },

  // Powai
  { city: "Mumbai", locality: "Powai", year: 2022, quarter: "Q1", averagePricePerSqm: 195000, transactionVolume: 92, newLaunchCount: 1 },
  { city: "Mumbai", locality: "Powai", year: 2023, quarter: "Q1", averagePricePerSqm: 210000, transactionVolume: 110, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Powai", year: 2024, quarter: "Q1", averagePricePerSqm: 222000, transactionVolume: 130, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Powai", year: 2025, quarter: "Q1", averagePricePerSqm: 230000, transactionVolume: 145, newLaunchCount: 1 },

  // Worli
  { city: "Mumbai", locality: "Worli", year: 2022, quarter: "Q1", averagePricePerSqm: 395000, transactionVolume: 42, newLaunchCount: 0 },
  { city: "Mumbai", locality: "Worli", year: 2023, quarter: "Q1", averagePricePerSqm: 420000, transactionVolume: 55, newLaunchCount: 1 },
  { city: "Mumbai", locality: "Worli", year: 2024, quarter: "Q1", averagePricePerSqm: 445000, transactionVolume: 65, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Worli", year: 2025, quarter: "Q1", averagePricePerSqm: 460000, transactionVolume: 78, newLaunchCount: 1 },

  // SG Highway
  { city: "Ahmedabad", locality: "Sarkhej-Gandhinagar Highway", year: 2022, quarter: "Q1", averagePricePerSqm: 68000, transactionVolume: 155, newLaunchCount: 3 },
  { city: "Ahmedabad", locality: "Sarkhej-Gandhinagar Highway", year: 2023, quarter: "Q1", averagePricePerSqm: 72000, transactionVolume: 180, newLaunchCount: 4 },
  { city: "Ahmedabad", locality: "Sarkhej-Gandhinagar Highway", year: 2024, quarter: "Q1", averagePricePerSqm: 78000, transactionVolume: 210, newLaunchCount: 5 },
  { city: "Ahmedabad", locality: "Sarkhej-Gandhinagar Highway", year: 2025, quarter: "Q1", averagePricePerSqm: 82000, transactionVolume: 230, newLaunchCount: 3 },

  // Wakad
  { city: "Pune", locality: "Wakad", year: 2022, quarter: "Q1", averagePricePerSqm: 65000, transactionVolume: 120, newLaunchCount: 2 },
  { city: "Pune", locality: "Wakad", year: 2023, quarter: "Q1", averagePricePerSqm: 69000, transactionVolume: 145, newLaunchCount: 3 },
  { city: "Pune", locality: "Wakad", year: 2024, quarter: "Q1", averagePricePerSqm: 74000, transactionVolume: 160, newLaunchCount: 2 },
  { city: "Pune", locality: "Wakad", year: 2025, quarter: "Q1", averagePricePerSqm: 78000, transactionVolume: 185, newLaunchCount: 4 },

  // Adajan
  { city: "Surat", locality: "Adajan", year: 2022, quarter: "Q1", averagePricePerSqm: 48000, transactionVolume: 80, newLaunchCount: 1 },
  { city: "Surat", locality: "Adajan", year: 2023, quarter: "Q1", averagePricePerSqm: 51000, transactionVolume: 92, newLaunchCount: 2 },
  { city: "Surat", locality: "Adajan", year: 2024, quarter: "Q1", averagePricePerSqm: 55000, transactionVolume: 110, newLaunchCount: 1 },
  { city: "Surat", locality: "Adajan", year: 2025, quarter: "Q1", averagePricePerSqm: 58000, transactionVolume: 125, newLaunchCount: 2 },

  // Pokhran Road
  { city: "Mumbai", locality: "Pokhran Road", year: 2022, quarter: "Q1", averagePricePerSqm: 142000, transactionVolume: 65, newLaunchCount: 1 },
  { city: "Mumbai", locality: "Pokhran Road", year: 2023, quarter: "Q1", averagePricePerSqm: 150000, transactionVolume: 80, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Pokhran Road", year: 2024, quarter: "Q1", averagePricePerSqm: 160000, transactionVolume: 95, newLaunchCount: 2 },
  { city: "Mumbai", locality: "Pokhran Road", year: 2025, quarter: "Q1", averagePricePerSqm: 168000, transactionVolume: 110, newLaunchCount: 1 },

  // Science City
  { city: "Ahmedabad", locality: "Science City", year: 2022, quarter: "Q1", averagePricePerSqm: 65000, transactionVolume: 120, newLaunchCount: 2 },
  { city: "Ahmedabad", locality: "Science City", year: 2023, quarter: "Q1", averagePricePerSqm: 71000, transactionVolume: 135, newLaunchCount: 3 },
  { city: "Ahmedabad", locality: "Science City", year: 2024, quarter: "Q1", averagePricePerSqm: 82000, transactionVolume: 150, newLaunchCount: 4 },
  { city: "Ahmedabad", locality: "Science City", year: 2025, quarter: "Q1", averagePricePerSqm: 89000, transactionVolume: 170, newLaunchCount: 2 },

  // Thane West
  { city: "Mumbai", locality: "Thane West", year: 2022, quarter: "Q1", averagePricePerSqm: 155000, transactionVolume: 210, newLaunchCount: 5 },
  { city: "Mumbai", locality: "Thane West", year: 2023, quarter: "Q1", averagePricePerSqm: 168000, transactionVolume: 240, newLaunchCount: 4 },
  { city: "Mumbai", locality: "Thane West", year: 2024, quarter: "Q1", averagePricePerSqm: 178000, transactionVolume: 280, newLaunchCount: 6 },
  { city: "Mumbai", locality: "Thane West", year: 2025, quarter: "Q1", averagePricePerSqm: 185000, transactionVolume: 310, newLaunchCount: 3 },

  // Hinjewadi
  { city: "Pune", locality: "Hinjewadi", year: 2022, quarter: "Q1", averagePricePerSqm: 62000, transactionVolume: 180, newLaunchCount: 4 },
  { city: "Pune", locality: "Hinjewadi", year: 2023, quarter: "Q1", averagePricePerSqm: 68000, transactionVolume: 210, newLaunchCount: 5 },
  { city: "Pune", locality: "Hinjewadi", year: 2024, quarter: "Q1", averagePricePerSqm: 74000, transactionVolume: 250, newLaunchCount: 6 },
  { city: "Pune", locality: "Hinjewadi", year: 2025, quarter: "Q1", averagePricePerSqm: 79000, transactionVolume: 290, newLaunchCount: 4 },

  // Vesu
  { city: "Surat", locality: "Vesu", year: 2022, quarter: "Q1", averagePricePerSqm: 52000, transactionVolume: 90, newLaunchCount: 1 },
  { city: "Surat", locality: "Vesu", year: 2023, quarter: "Q1", averagePricePerSqm: 57000, transactionVolume: 110, newLaunchCount: 2 },
  { city: "Surat", locality: "Vesu", year: 2024, quarter: "Q1", averagePricePerSqm: 63000, transactionVolume: 130, newLaunchCount: 3 },
  { city: "Surat", locality: "Vesu", year: 2025, quarter: "Q1", averagePricePerSqm: 68000, transactionVolume: 145, newLaunchCount: 1 }
];

const priceForecasts = [
  {
    city: "Ahmedabad",
    locality: "Thaltej",
    forecastModel: "Random Forest Regressor",
    currentPricePerSqm: 96000,
    forecast_6m: 99200,
    forecast_1y: 104500,
    forecast_5y: 138000,
    growthProbability: 0.89,
    rentalYieldPercent: 3.2
  },
  {
    city: "Ahmedabad",
    locality: "Science City",
    forecastModel: "Random Forest Regressor",
    currentPricePerSqm: 89000,
    forecast_6m: 92800,
    forecast_1y: 98100,
    forecast_5y: 132000,
    growthProbability: 0.94,
    rentalYieldPercent: 2.9
  },
  {
    city: "Mumbai",
    locality: "Lower Parel",
    forecastModel: "Gradient Boosting Regressor",
    currentPricePerSqm: 365000,
    forecast_6m: 374000,
    forecast_1y: 388000,
    forecast_5y: 495000,
    growthProbability: 0.78,
    rentalYieldPercent: 2.4
  },
  {
    city: "Mumbai",
    locality: "Thane West",
    forecastModel: "Random Forest Regressor",
    currentPricePerSqm: 185000,
    forecast_6m: 191000,
    forecast_1y: 201000,
    forecast_5y: 275000,
    growthProbability: 0.91,
    rentalYieldPercent: 3.5
  },
  {
    city: "Pune",
    locality: "Hinjewadi",
    forecastModel: "Linear Regression Fallback",
    currentPricePerSqm: 79000,
    forecast_6m: 81500,
    forecast_1y: 85200,
    forecast_5y: 108000,
    growthProbability: 0.85,
    rentalYieldPercent: 4.1
  },
  {
    city: "Surat",
    locality: "Vesu",
    forecastModel: "Linear Regression Fallback",
    currentPricePerSqm: 68000,
    forecast_6m: 70800,
    forecast_1y: 74200,
    forecast_5y: 96000,
    growthProbability: 0.88,
    rentalYieldPercent: 3.6
  },
  {
    city: "Mumbai",
    locality: "Powai",
    forecastModel: "Gradient Boosting Regressor",
    currentPricePerSqm: 230000,
    forecast_6m: 238000,
    forecast_1y: 248000,
    forecast_5y: 320000,
    growthProbability: 0.92,
    rentalYieldPercent: 3.4
  },
  {
    city: "Mumbai",
    locality: "Worli",
    forecastModel: "Gradient Boosting Regressor",
    currentPricePerSqm: 460000,
    forecast_6m: 472000,
    forecast_1y: 490000,
    forecast_5y: 610000,
    growthProbability: 0.85,
    rentalYieldPercent: 2.2
  },
  {
    city: "Ahmedabad",
    locality: "Sarkhej-Gandhinagar Highway",
    forecastModel: "Random Forest Regressor",
    currentPricePerSqm: 82000,
    forecast_6m: 85500,
    forecast_1y: 91000,
    forecast_5y: 122000,
    growthProbability: 0.94,
    rentalYieldPercent: 3.1
  },
  {
    city: "Pune",
    locality: "Wakad",
    forecastModel: "Linear Regression Fallback",
    currentPricePerSqm: 78000,
    forecast_6m: 80800,
    forecast_1y: 84500,
    forecast_5y: 108000,
    growthProbability: 0.88,
    rentalYieldPercent: 3.9
  },
  {
    city: "Surat",
    locality: "Adajan",
    forecastModel: "Linear Regression Fallback",
    currentPricePerSqm: 58000,
    forecast_6m: 60200,
    forecast_1y: 63000,
    forecast_5y: 79000,
    growthProbability: 0.81,
    rentalYieldPercent: 3.5
  },
  {
    city: "Mumbai",
    locality: "Pokhran Road",
    forecastModel: "Random Forest Regressor",
    currentPricePerSqm: 168000,
    forecast_6m: 174000,
    forecast_1y: 182000,
    forecast_5y: 245000,
    growthProbability: 0.89,
    rentalYieldPercent: 3.3
  }
];

const fraudReports = [
  {
    title: "Project Construction Latency Alert",
    targetType: "Project",
    identifier: "P52100026453", // Life Republic
    city: "Pune",
    anomalyType: "Repeated Delays",
    riskLevel: "High",
    description: "Project delay has exceeded 13 months beyond the original RERA-declared completion date. Ongoing environmental clearance litigation detected.",
    evidence: { delayedMonths: 13, legalDisputeFlags: true }
  },
  {
    title: "Sale Deed Circle Rate Violation Detect",
    targetType: "Transaction",
    identifier: "MUM/LP/2025/1102",
    city: "Mumbai",
    anomalyType: "Circle Rate Discrepancy",
    riskLevel: "High",
    description: "Property sold at 35.48% BELOW the state-mandated circular/stamp duty rate for Lower Parel locality. Suggests potential under-valuation or tax avoidance anomaly.",
    evidence: { transactionRate: 200000, circleRate: 310000, variancePercentage: -35.48 }
  },
  {
    title: "Duplicate Survey Registration Conflict",
    targetType: "Land Record",
    identifier: "302/B",
    city: "Thane",
    anomalyType: "Duplicate Survey Registration",
    riskLevel: "Medium",
    description: "Same land parcel index reported dual transaction mutation logs across two different sub-registrar filings within a 60-day period.",
    evidence: { surveyNumber: "302/B", village: "Dombivli", overlapPercentage: 100 }
  },
  {
    title: "Deed Circle Rate Deficit Warning",
    targetType: "Transaction",
    identifier: "AMD/SGH/2025/0981",
    city: "Ahmedabad",
    anomalyType: "Circle Rate Discrepancy",
    riskLevel: "Medium",
    description: "Stamp valuation discrepancy detected. SG Highway office transaction registered slightly below historical averages.",
    evidence: { transactionRate: 80000, circleRate: 72000, variancePercentage: 11.1 }
  },
  {
    title: "Developer Trust Score Revision",
    targetType: "Builder",
    identifier: "ATHSL1102A",
    city: "Mumbai",
    anomalyType: "Repeated Delays",
    riskLevel: "Medium",
    description: "Tata Serein recorded 4 months delay in occupation certificate deliveries, triggering trust rating calibration.",
    evidence: { delayedMonths: 4, legalDisputeFlags: false }
  }
];

const governmentDatasets = [
  {
    datasetName: "MahaRERA Project Registrations API",
    sourcePortal: "maharera.mahaonline.gov.in",
    dataType: "RERA Projects",
    refreshFrequency: "Daily",
    lastSyncTime: new Date("2026-07-02T10:30:00Z"),
    syncStatus: "Operational",
    recordCount: 45290,
    errorLogsCount: 0
  },
  {
    datasetName: "Gujarat RERA Developer Database",
    sourcePortal: "gujrera.gujarat.gov.in",
    dataType: "RERA Projects",
    refreshFrequency: "Daily",
    lastSyncTime: new Date("2026-07-02T11:15:00Z"),
    syncStatus: "Operational",
    recordCount: 18230,
    errorLogsCount: 0
  },
  {
    datasetName: "IGR Maharashtra Sale Deeds Ledger",
    sourcePortal: "igrmaharashtra.gov.in",
    dataType: "Stamp Duty Transactions",
    refreshFrequency: "Weekly",
    lastSyncTime: new Date("2026-06-28T04:00:00Z"),
    syncStatus: "Operational",
    recordCount: 894000,
    errorLogsCount: 4
  },
  {
    datasetName: "Smart City Mission Urban Development Projects",
    sourcePortal: "smartcities.gov.in",
    dataType: "Smart City Projects",
    refreshFrequency: "Monthly",
    lastSyncTime: new Date("2026-06-15T09:00:00Z"),
    syncStatus: "Operational",
    recordCount: 1420,
    errorLogsCount: 0
  },
  {
    datasetName: "AnyROR Gujarat Land Survey Registry",
    sourcePortal: "anyror.gujarat.gov.in",
    dataType: "Land Survey Records",
    refreshFrequency: "Weekly",
    lastSyncTime: new Date("2026-07-01T18:00:00Z"),
    syncStatus: "Degraded",
    recordCount: 340200,
    errorLogsCount: 18
  }
];

const notifications = [
  {
    title: "MahaRERA Sync Completed",
    message: "Data sync pipeline crawled 42 new project filings in Thane and Lower Parel successfully.",
    type: "SystemUpdate",
    isRead: false
  },
  {
    title: "Growth Index Alert: Thaltej",
    message: "Growth score of Thaltej increased from 86 to 88 due to the newly approved Science City Metro station layout.",
    type: "GrowthInsight",
    isRead: false
  },
  {
    title: "Builder Trust Score Warning",
    message: "Sunteck Realty Trust Score fell to 74 following an unresolved legal dispute filed at MahaRERA regarding a Vasai project.",
    type: "FraudWarning",
    isRead: true
  }
];

const systemLogs = [
  { level: "info", message: "Express server initialized successfully", component: "API-Server" },
  { level: "info", message: "Connecting to local MongoDB at 127.0.0.1:27017/real_estate_db", component: "API-Server" },
  { level: "warn", message: "Redis client could not connect. Falling back to in-memory caching engine.", component: "API-Server" },
  { level: "info", message: "Scheduled GujRERA project crawler task completed. Processed 14 records, 0 errors.", component: "Crawler-GujRERA" },
  { level: "info", message: "Scheduled MahaRERA developer tracking task completed. Sync status: Operational.", component: "Crawler-MahaRERA" },
  { level: "info", message: "AI Engine predicted 6m, 1y, 5y prices for 6 core localities in 0.42 seconds.", component: "AI-Engine" }
];

module.exports = {
  builders,
  reraProjects,
  landRecords,
  propertyTransactions,
  areaAnalytics,
  infrastructureProjects,
  historicalMarketData,
  priceForecasts,
  fraudReports,
  governmentDatasets,
  notifications,
  systemLogs
};
